name: Extract and load data

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud (WIF)
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/834426860635/locations/global/workloadIdentityPools/github-pool/providers/github-actions"
          service_account: "bot-drive-contable@drive-contable.iam.gserviceaccount.com"

      - name: Build Docker image
        run: docker build -t contable-scraper .

      - name: Run scraping container
        env:
          MAIL_USER: ${{ secrets.MAIL_USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          docker run \
            -e MAIL_USER="$MAIL_USER" \
            -e PASSWORD="$PASSWORD" \
            contable-scraper
